/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SuitElemenGame;

import static SuitElemenGame.HalPemain1.kontrolGamee;
import static SuitElemenGame.HalPemain1.pemain1;
import static SuitElemenGame.HalPemain1.waktuTersisa;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author rizal
 */
public class HalPemain2 extends javax.swing.JFrame {
    public static Pemain pemain1;
    public static Pemain pemain2;
    public static int ronde;
    public static KontrolGamee kontrolGamee;
    public Timer timer;
    public static int waktuTersisa;

    /**
     * Creates new form Player2
     */
    public HalPemain2(Pemain pemain1, Pemain pemain2, int ronde) {
        HalPemain2.pemain1 = pemain1;
        HalPemain2.pemain2 = pemain2;
        this.ronde = ronde;
        initComponents();
        LRonde.setText("RONDE " + Integer.toString(ronde));
        LNamaPemain2.setText(pemain2.getNama());
        LHpPemain2.setText("HP : " + Integer.toString(pemain2.getHp()));
        waktuTersisa = 10;
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(waktuTersisa > 0) {
                    waktuTersisa--;
                    LTimer.setText("Waktu tersisa : " + waktuTersisa + "detik");    
                } else {
                    timer.stop();
                    if(pemain2.getPilihan() == null && pemain2.getElemen() == null) {
                        kontrolGamee.randomPilihan(pemain2);
                        kontrolGamee.randomElemen(pemain2);
                        System.out.println("dua-dua null");
                        System.out.println(pemain2.getPilihan());
                        System.out.println(pemain2.getElemen());
                        HalPemenang halPemenang = new HalPemenang(pemain1, pemain2, ronde);
                        halPemenang.setVisible(true);
                        HalPemain2.this.dispose();
                    } else if(pemain2.getPilihan() == null && pemain2.getElemen() != null) {
                        KontrolGamee.randomPilihan(pemain2);
                        System.out.println("pilihan kosong");
                        System.out.println(pemain2.getPilihan());
                        System.out.println(pemain2.getElemen());
                        HalPemenang halPemenang = new HalPemenang(pemain1, pemain2, ronde);
                        halPemenang.setVisible(true);
                        HalPemain2.this.dispose();
                    } else if(pemain2.getElemen() == null && pemain2.getPilihan() != null) {
                        KontrolGamee.randomElemen(pemain2);
                        System.out.println("elemen kosong");
                        System.out.println(pemain2.getPilihan());
                        System.out.println(pemain2.getElemen());
                        HalPemenang halPemenang = new HalPemenang(pemain1, pemain2, ronde);
                        halPemenang.setVisible(true);
                        HalPemain2.this.dispose();
                    } else {
                        HalTungguPemain2 halTungguPemain2 = new HalTungguPemain2(pemain1, pemain2, ronde);
                        System.out.println("elemen dan pilihan tidak kosong");
                        System.out.println(pemain1.getPilihan());
                        System.out.println(pemain1.getElemen());
                        halTungguPemain2.setVisible(true);
                        HalPemain2.this.dispose();
                    }
                }
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BBatu = new javax.swing.JButton();
        BKertas = new javax.swing.JButton();
        BGunting = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BAir = new javax.swing.JButton();
        BAngin = new javax.swing.JButton();
        BApi = new javax.swing.JButton();
        BTanah = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        LRonde = new javax.swing.JLabel();
        LNamaPemain2 = new javax.swing.JLabel();
        LHpPemain2 = new javax.swing.JLabel();
        LTimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tentukan Pilihan Suit");

        BBatu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BBatu.setText("Batu");
        BBatu.setPreferredSize(new java.awt.Dimension(100, 32));
        BBatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatuActionPerformed(evt);
            }
        });

        BKertas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BKertas.setText("Kertas");
        BKertas.setPreferredSize(new java.awt.Dimension(100, 32));
        BKertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKertasActionPerformed(evt);
            }
        });

        BGunting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BGunting.setText("Gunting");
        BGunting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuntingActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pilih Elemen");

        BAir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BAir.setText("Air");
        BAir.setPreferredSize(new java.awt.Dimension(85, 32));
        BAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAirActionPerformed(evt);
            }
        });

        BAngin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BAngin.setText("Angin");
        BAngin.setPreferredSize(new java.awt.Dimension(85, 32));
        BAngin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnginActionPerformed(evt);
            }
        });

        BApi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BApi.setText("Api");
        BApi.setPreferredSize(new java.awt.Dimension(85, 32));
        BApi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BApiActionPerformed(evt);
            }
        });

        BTanah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTanah.setText("Tanah");
        BTanah.setPreferredSize(new java.awt.Dimension(85, 32));
        BTanah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTanahActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Lanjut");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        LRonde.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LRonde.setForeground(new java.awt.Color(255, 255, 255));
        LRonde.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LRonde.setText("Ronde");

        LNamaPemain2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LNamaPemain2.setForeground(new java.awt.Color(255, 255, 255));
        LNamaPemain2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LNamaPemain2.setText("Nama");

        LHpPemain2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LHpPemain2.setForeground(new java.awt.Color(255, 255, 255));
        LHpPemain2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LHpPemain2.setText("HP : ");

        LTimer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LTimer.setForeground(new java.awt.Color(255, 255, 255));
        LTimer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LTimer.setText("Waktu tersisa :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 218, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BTanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BApi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BAngin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LNamaPemain2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LRonde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(LHpPemain2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BGunting)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BBatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BKertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(233, 233, 233))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(327, 327, 327))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LRonde)
                    .addComponent(LTimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNamaPemain2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LHpPemain2)
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BKertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BGunting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BApi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAngin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BGuntingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuntingActionPerformed
        // TODO add your handling code here:
        pemain2.setPilihan("gunting");
        BGunting.setForeground(Color.red);
        BKertas.setForeground(Color.black);
        BBatu.setForeground(Color.black);
    }//GEN-LAST:event_BGuntingActionPerformed

    private void BBatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatuActionPerformed
        // TODO add your handling code here:
        pemain2.setPilihan("batu");
        BBatu.setForeground(Color.red);
        BGunting.setForeground(Color.black);
        BKertas.setForeground(Color.black);
    }//GEN-LAST:event_BBatuActionPerformed

    private void BKertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKertasActionPerformed
        // TODO add your handling code here:
        pemain2.setPilihan("kertas");
        BKertas.setForeground(Color.red);
        BBatu.setForeground(Color.black);
        BGunting.setForeground(Color.black);
    }//GEN-LAST:event_BKertasActionPerformed

    private void BTanahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTanahActionPerformed
        // TODO add your handling code here:
        pemain2.setElemen("tanah");
        BTanah.setForeground(Color.red);
        BApi.setForeground(Color.black);
        BAir.setForeground(Color.black);
        BAngin.setForeground(Color.black);
    }//GEN-LAST:event_BTanahActionPerformed

    private void BAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAirActionPerformed
        // TODO add your handling code here:
        pemain2.setElemen("air");
        BAir.setForeground(Color.red);
        BApi.setForeground(Color.black);
        BTanah.setForeground(Color.black);
        BAngin.setForeground(Color.black);
    }//GEN-LAST:event_BAirActionPerformed

    private void BApiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BApiActionPerformed
        // TODO add your handling code here:
        pemain2.setElemen("api");
        BApi.setForeground(Color.red);
        BTanah.setForeground(Color.black);
        BAir.setForeground(Color.black);
        BAngin.setForeground(Color.black);
    }//GEN-LAST:event_BApiActionPerformed

    private void BAnginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnginActionPerformed
        // TODO add your handling code here:
        pemain2.setElemen("angin");
        BAngin.setForeground(Color.red);
        BTanah.setForeground(Color.black);
        BAir.setForeground(Color.black);
        BApi.setForeground(Color.black);
    }//GEN-LAST:event_BAnginActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        HalPemenang halPemenang = new HalPemenang(pemain1, pemain2, ronde);
        halPemenang.setVisible(true);
        timer.stop();
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalPemain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalPemain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalPemain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalPemain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalPemain2(pemain1, pemain2, ronde).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAir;
    private javax.swing.JButton BAngin;
    private javax.swing.JButton BApi;
    private javax.swing.JButton BBatu;
    private javax.swing.JButton BGunting;
    private javax.swing.JButton BKertas;
    private javax.swing.JButton BTanah;
    private javax.swing.JLabel LHpPemain2;
    private javax.swing.JLabel LNamaPemain2;
    private javax.swing.JLabel LRonde;
    private javax.swing.JLabel LTimer;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
